pre-commit:
  - id: scalafmt
    main: org.scalafmt.cli.Cli
    dependencies:
      - org.scalameta:scalafmt-cli_2.13:3.7.17
    args: ["--non-interactive"]
  
  - id: compile-check
    command: sbt
    args: ["compile"]
